# Labeler configuration for automatic PR labeling

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'pnpm-lock.yaml']

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

'styling':
  - changed-files:
    - any-glob-to-any-file: ['**/*.css', '**/*.scss', '**/*.sass']

'vue-components':
  - changed-files:
    - any-glob-to-any-file: ['src/components/**/*.vue']

'views':
  - changed-files:
    - any-glob-to-any-file: ['src/views/**/*.vue']

'tests':
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.js', '**/*.spec.js', 'tests/**/*']

'ci/cd':
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', 'netlify.toml', 'Dockerfile', 'docker-compose.yml']

'assets':
  - changed-files:
    - any-glob-to-any-file: ['public/**/*', 'src/assets/**/*']

'config':
  - changed-files:
    - any-glob-to-any-file: ['*.config.js', '*.config.ts', '.eslintrc*', '.prettierrc*', 'tsconfig.json']
