version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:80"
    container_name: portfolio-vue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VUE_APP_SANITY_PROJECT_ID=${VUE_APP_SANITY_PROJECT_ID}
      - VUE_APP_SANITY_DATASET=${VUE_APP_SANITY_DATASET}
      - VUE_APP_SANITY_API_VERSION=${VUE_APP_SANITY_API_VERSION}
      - VUE_APP_SANITY_USE_CDN=${VUE_APP_SANITY_USE_CDN}
    networks:
      - portfolio-network

  # Optional: Development container
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: portfolio-vue-dev
    environment:
      - NODE_ENV=development
      - VUE_APP_SANITY_PROJECT_ID=${VUE_APP_SANITY_PROJECT_ID}
      - VUE_APP_SANITY_DATASET=${VUE_APP_SANITY_DATASET}
      - VUE_APP_SANITY_API_VERSION=${VUE_APP_SANITY_API_VERSION}
      - VUE_APP_SANITY_USE_CDN=${VUE_APP_SANITY_USE_CDN}
    networks:
      - portfolio-network
    profiles:
      - dev

networks:
  portfolio-network:
    driver: bridge